#!/usr/bin/env bash

# Check the number of arguments passed
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Get the arguments
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Disable strict host key checking
ssh -o StrictHostKeyChecking=no -i "$ssh_key_path" "$username@$server_ip" << EOF
  # Move the file to the user's home directory
  scp -i "$ssh_key_path" "$file_path" ~/
EOF

# Check for errors
if [ $? -ne 0 ]; then
  echo "Error transferring file."
  exit 1
fi

echo "File transferred successfully."
