#!/usr/bin/env bash
#Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu

#!/usr/bin/env bash
# Allows us to connect to my server using the private key with user ubuntu
ssh -i ~/.ssh/id_rsa ubuntu@100.26.20.17
